// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by Prisma Migrate / CLI. Use Supabase's DIRECT connection
    // (port 5432) here — migrations don't work over the pooled PgBouncer URL.
    // The runtime PrismaClient connects via the pg driver adapter (DATABASE_URL).
    url: process.env["DIRECT_URL"],
  },
});
